### ISSUE TITLE
LogBlock (plugin) fails to connect to MySQL database.

### ISSUE THREAD

**Issue by FaintingHope** [FaintingHope/lotfmc#2]
LogBlock fails to connect to MySql database with the following error message.

`Console	: [23:32:14 ERROR]: [LogBlock] Error while fetching connection: 
Console	: com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Communications link failure
Console	: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Console	: 	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:581) ~[LogBlock.jar:?]
Console	: 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:152) ~[LogBlock.jar:?]
Console	: 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[LogBlock.jar:?]
Console	: 	at de.diddiz.util.MySQLConnectionPool.getConnection(MySQLConnectionPool.java:38) ~[LogBlock.jar:?]
Console	: 	at de.diddiz.LogBlock.LogBlock.getConnection(LogBlock.java:263) [LogBlock.jar:?]
Console	: 	at de.diddiz.LogBlock.LogBlock.onLoad(LogBlock.java:63) [LogBlock.jar:?]
Console	: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307) [spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Console	: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
Console	: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Console	: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
Console	: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
Console	: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
Console	: 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_131]
Console	: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2192) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2225) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2024) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
Console	: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
Console	: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
Console	: 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_131]
Console	: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
Console	: 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
Console	: 	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496) ~[?:?]
Console	: 	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565) ~[?:?]
Console	: 	... 9 more
Console	: Caused by: java.net.ConnectException: Connection refused: connect
Console	: 	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_131]
Console	: 	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_131]
Console	: 	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_131]
Console	: 	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_131]
Console	: 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_131]
Console	: 	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_131]
Console	: 	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_131]
Console	: 	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_131]
Console	: 	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2192) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2225) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2024) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
Console	: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
Console	: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
Console	: 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_131]
Console	: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[spigot.jar:git-Spigot-23b6354-0481ae9]
Console	: 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[?:?]
Console	: 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[?:?]
Console	: 	at com.zaxxer.hikari.pool.HikariPool.addConnection(HikariPool.java:496) ~[?:?]
Console	: 	at com.zaxxer.hikari.pool.HikariPool.initializeConnections(HikariPool.java:565) ~[?:?]
Console	: 	... 9 more`

**Comment by FaintingHope** [comment]
No MySQL table has been setup to allow connection. This is an expected error.
